// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  postgresSidebar: [
    {
      type: 'category',
      label: 'Примеры переводов',
      items: 
	[
	  {
	  type: 'autogenerated',
	  dirName: 'samples',
	  },
	],
    },
    {
      type: 'category',
      label: 'Postgres',
      items: ['ecpg-variables'],
    },

    {
      type: 'category',
      label: 'Preface',
      link: {
	type: 'doc',
	id: 'preface',
	    },
      items: [ { type: 'autogenerated', dirName: 'preface',}, ],
    },

    {
      type: 'category',
      label: 'I. Tutorial',
      link: {
	type: 'doc',
	id: 'tutorial',
	    },
      	items: [
	        {
      	          type: 'category',
      		  label: '1. Getting Started',
      		  link: {
		    type: 'doc',
		    id: 'I. Tutorial/tutorial-start',
	    	        },
		    items:
			[ { type: 'autogenerated',
			    dirName: 'tutorial/gettingstarted',}, ],
	        },
	        {
      	          type: 'category',
      		  label: '2. The SQL Language',
      		  link: {
		    type: 'doc',
		    id: 'I. Tutorial/tutorial-sql',
	    	        },
		    items:
			[ { type: 'autogenerated',
			    dirName: 'I. Tutorial/2. The SQL Language',}, ],
	        },
	        {
      	          type: 'category',
      		  label: '3. Advanced Features',
      		  link: {
		    type: 'doc',
		    id: 'I. Tutorial/tutorial-advanced',
	    	        },
		    items:
			[ { type: 'autogenerated',
			    dirName: 'I. Tutorial/3. Advanced Features',}, ],
	        },
	       ],
    },

    {
      type: 'category',
      label: 'II. The SQL Language',
      link: {
	type: 'doc',
	id: 'sql',
	    },
	items:
	  [
        {
          type: 'category',
	  label: '4. SQL Syntax',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/sql-syntax',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/4. SQL Syntax',}, ],
        },
        {
          type: 'category',
	  label: '5. Data Definition',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/ddl',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/5. Data Definition',}, ],
        },
        {
          type: 'category',
	  label: '6. Data Manipulation',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/dml',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/6. Data Manipulation',}, ],
        },
        {
          type: 'category',
	  label: '7. Queries',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/queries',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/7. Queries',}, ],
        },
        {
          type: 'category',
	  label: '8. Data Types',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/datatype',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/8. Data Types',}, ],
        },
        {
          type: 'category',
	  label: '9. Functions and Operators',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/functions',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/9. Functions and Operators',}, ],
        },
        {
          type: 'category',
	  label: '10. Type Conversion',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/typeconv',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/10. Type Conversion',}, ],
        },
        {
          type: 'category',
	  label: '11. Indexes',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/indexes',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/11. Indexes',}, ],
        },
        {
          type: 'category',
	  label: '12. Full Text Search',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/textsearch',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/12. Full Text Search',}, ],
        },
        {
          type: 'category',
	  label: '13. Concurrency Control',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/mvcc',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/13. Concurrency Control',}, ],
        },
        {
          type: 'category',
	  label: '14. Performance Tips',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/performance-tips',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/14. Performance Tips',}, ],
        },
        {
          type: 'category',
	  label: '15. Parallel Query',
	  link: {
	    type: 'doc',
	    id: 'II. The SQL Language/parallel-query',
    	        },
	    items:
		[ { type: 'autogenerated',
		    dirName: 'II. The SQL Language/15. Parallel Query',}, ],
        },
	  ],
    },


    {
      type: 'category',
      label: 'III. Server Administration',
      link: {
	type: 'doc',
	id: 'admin',
	    },
	items:
	  ['III. Server Administration/install-binaries',
	    {
	     type: 'category',
	     label: '17. Installation from Source Code',
	     link: {
	       type: 'doc',
	       id: 'III. Server Administration/installation',
		},
	       items: 
		[
  		  {
	            type: 'autogenerated',
		    dirName: 'III. Server Administration/17. Installation from Source Code',
		  },
		],
	    },
	    {
	     type: 'category',
	     label: '18. Installation from Source Code on Windows',
	     link: {
	       type: 'doc',
	       id: 'III. Server Administration/installation',
		},
	       items: 
		[
  		  {
	            type: 'autogenerated',
		    dirName: 'III. Server Administration/18. Installation from Source Code on Windows',
		  },
		],
	    },
	    {
	     type: 'category',
	     label: '19. Server Setup and Operation',
	     link: {
	       type: 'doc',
	       id: 'III. Server Administration/runtime',
		},
	       items: 
		[
  		  {
	            type: 'autogenerated',
		    dirName: 'III. Server Administration/19. Server Setup and Operation',
		  },
		],
	    },
	    {
	     type: 'category',
	     label: '20. Server Configuration',
	     link: {
	       type: 'doc',
	       id: 'III. Server Administration/runtime-config',
		},
	       items: 
		[
  		  {
	            type: 'autogenerated',
		    dirName: 'III. Server Administration/20. Server Configuration',
		  },
		],
	    },


	  ],
    },

  ],
};

export default sidebars;
